[package]
name = "image_convert"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
image = { version = "0.25.8", features = ["default-formats"] }
js-sys = "0.3.78"
wasm-bindgen = "0.2.101"
